from django.urls import path

from .views import (
    CartItemDetailView,
    CartItemsView,
    CartView,
    CheckoutPlaceOrderView,
    CheckoutPrefillView,
    CheckoutSummaryView,
    AdminDeliveryOptionDetailView,
    AdminDeliveryOptionListCreateView,
    AdminOrderStatusUpdateView,
    AdminRefundListView,
    AdminRefundStatusUpdateView,
    OrderCancelView,
    OrderDetailView,
    OrderListView,
    OrderProcessView,
    PaymentCallbackSimulationView,
    PaymentConfigView,
    RefundRequestListCreateView,
)

urlpatterns = [
    path("cart/", CartView.as_view(), name="commerce_cart"),
    path("cart/items/", CartItemsView.as_view(), name="commerce_cart_items"),
    path("cart/items/<int:item_id>/", CartItemDetailView.as_view(), name="commerce_cart_item_detail"),
    path("checkout/prefill/", CheckoutPrefillView.as_view(), name="commerce_checkout_prefill"),
    path("checkout/payment-config/", PaymentConfigView.as_view(), name="commerce_payment_config"),
    path("payments/callback/", PaymentCallbackSimulationView.as_view(), name="commerce_payment_callback"),
    path("checkout/summary/", CheckoutSummaryView.as_view(), name="commerce_checkout_summary"),
    path("checkout/place-order/", CheckoutPlaceOrderView.as_view(), name="commerce_checkout_place_order"),
    path("orders/", OrderListView.as_view(), name="commerce_order_list"),
    path("orders/<int:order_id>/", OrderDetailView.as_view(), name="commerce_order_detail"),
    path("orders/<int:order_id>/cancel/", OrderCancelView.as_view(), name="commerce_order_cancel"),
    path("orders/<int:order_id>/process/", OrderProcessView.as_view(), name="commerce_order_process"),
    path("refunds/", RefundRequestListCreateView.as_view(), name="commerce_refund_list_create"),
    path("admin/delivery-options/", AdminDeliveryOptionListCreateView.as_view(), name="commerce_admin_delivery_options"),
    path("admin/delivery-options/<int:option_id>/", AdminDeliveryOptionDetailView.as_view(), name="commerce_admin_delivery_option_detail"),
    path("admin/orders/<int:order_id>/status/", AdminOrderStatusUpdateView.as_view(), name="commerce_admin_order_status"),
    path("admin/refunds/", AdminRefundListView.as_view(), name="commerce_admin_refund_list"),
    path("admin/refunds/<int:refund_id>/status/", AdminRefundStatusUpdateView.as_view(), name="commerce_admin_refund_status"),
]
