# Generated by Django 5.1.4 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_access_token_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('support', 'Support'), ('sales', 'Sales')], default='customer', max_length=20),
        ),
    ]
