# Generated by Django 5.1.4 on 2026-02-26

import hashlib

from django.db import migrations

import users.fields


def _hash(value: str) -> str:
    return hashlib.sha256(str(value).encode("utf-8")).hexdigest()


def migrate_sensitive_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    AccessTokenBlocklist = apps.get_model("users", "AccessTokenBlocklist")

    for user in User.objects.all().iterator():
        changed = False
        if user.full_name:
            changed = True
        if user.otp_secret:
            changed = True
        if changed:
            user.save(update_fields=["full_name", "otp_secret"])

    for block in AccessTokenBlocklist.objects.all().iterator():
        if block.jti and len(block.jti) != 64:
            block.jti = _hash(block.jti)
            block.save(update_fields=["jti"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=users.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_secret",
            field=users.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(migrate_sensitive_data, migrations.RunPython.noop),
    ]
